### ISSUE TITLE
Patching errors

### ISSUE THREAD

**Issue by BanchouBoo** [NoharOSP/Perfect_Works_Build#180]
When trying to apply the "Retranslated script" patch using the latest commit, I get this error
![image](https://user-images.githubusercontent.com/32691832/189235949-491b313b-279c-4728-adde-027f6d1ac782.png)

and when trying to apply the "Rebalanced party stats" patch I get this error popup twice but then it says completed the patch successfully
![image](https://user-images.githubusercontent.com/32691832/189236036-19b9ea0a-e54a-4351-a591-98fef8d3969b.png)

**Comment by NoharOSP** [comment]
You need to download the Mega or Google Drive link.
