### ISSUE TITLE
Use in conjunction with the undub patch

### ISSUE THREAD

**Issue by EtherAura** [NoharOSP/Perfect_Works_Build#181]
Hello - huge appreciation for the work that is being done here. I would like to use the Perfect Works patcher, but when used on the Undub  patched rom I am able to get to the title screen, but the menu options (new game, continue, sound) do not appear and I am unable to proceed with the game. I have tried applying the Undub patch (2.0 and the newer one from romhacking.net) both before and after using the Perfect Works patcher, to the same result. I have also tried it both with and without running the image through ECCregen.

I am experiencing the same results on both the Beetle and Swanstation RetroArch cores. If anyone can point me in the right direction I would be more than happy to help get the patches working together, or possibly contribute to integrating an undub into the Perfect Works patcher. : )

**Comment by NoharOSP** [comment]
Hello.

Thanks for reporting this. Outside of the button layout changer, the project is incompatible with both Undub hacks. I've tried making the two compatible earlier into the year to no avail. This has a lot to do with the changes to the ROM structure which some of the patches perform which clash with the changes to the game's executable file made by Undub. Admittedly, this is something that I should've explained on the README. 

I can't guarantee anything, but I'll try to see if I can get to the bottom of the issue for 0.2.

**Comment by NoharOSP** [comment]
Update to the situation for undub. In the project's current state (0.1.7); undub is compatible, but only if the ROM has been patched and regenerated first. After that, you can use the undub executable with it. The main glitch is that both the PW subtitles and the undub subtitles will appear during FMVs.

For verification; mednafen was used for testing, which is one of the most accurate PSX emulators.

**Comment by c-hoffmann** [comment]
@NoharOSP: Is there any update to this? The FAQ in the Readme still mentions both to be incompatible. Maybe the readme could link to your last post explaining the order of patching?
Also, I love that it works at least with this workaround! Is there anything that can be done concerning the double subtitles in FMVs?

**Comment by NoharOSP** [comment]
Based on the current state of the patcher, undub cannot be supported post 0.5.

**Comment by thekryz** [comment]
> Based on the current state of the patcher, undub cannot be supported post 0.5.

Thank you for the heads up! I might go for a version below 0.5 then.
