### ISSUE TITLE
Miang now heals 4200 HP for Ramsus during Babel tower battle

### ISSUE THREAD

**Issue by jianpan** [NoharOSP/Perfect_Works_Build#184]
Is this change intentional? It was 1200 HP in the original game. With this change, you pretty much have to one-shot kill Ramsus to finish the battle.

**Comment by NoharOSP** [comment]
Ramsus' HP here is 28,000 rather than 8000, meaning Myyah will always be healing by max HP / 6.6666666666666666666666666666667 regardless of version. Did you get an EtherDoubler from Nisan at all?

**Comment by jianpan** [comment]
I see. I did get EtherDoubler for Elly but she can only do about 3000 damage with Aerods. Given the increased 800 fuel consumption, she can use Aerods at most 3 times. Ramsus's 28000 HP in this mod is really steep.

**Comment by NoharOSP** [comment]
I'm going to suggest to nerf Wyvern down to 15000. 28000 is admittedly too steep from Stien's 13000. For now, does Elly have E-Circuits equipped?

**Comment by jianpan** [comment]
That sounds good. Thanks.

Yes Elly had E-Circuits when fighting Ramsus.

**Comment by NoharOSP** [comment]
Wyvern's HP is now 15000 in 0.1.7.
