### ISSUE TITLE
Text corruption in certain scenes (0.4.0)

### ISSUE THREAD

**Issue by Crackhog** [NoharOSP/Perfect_Works_Build#200]
I encountered weird, corrupted text in two instances while playing through version 0.4.0. The first time when fighting Elly in her gear, and the second time when Bart fought against the red gear. This is what the text looked like:
![SLUS-00664_2024-04-27_03-11-41](https://github.com/NoharOSP/Perfect_Works_Build/assets/62748103/a3f8dee4-27d3-4e83-8025-472fd006d64f)

The cause of this could likely be that I started the game using the Xenogears 2.0 patch first and switched to Perfect Works somewhere in the middle, but I wanted to make sure if that was really the case or if this was a bug in Perfect Works. 

I do not have a save file prior to the occurence sadly, so I can't really replicate it again.

**Comment by NoharOSP** [comment]
This scene has been fixed in 0.4.1, though here is a similar problem with the scene between Ramsus and Id a little later on. The fix for that will be given in 0.4.2.

**Comment by Crackhog** [comment]
That's great, thanks for your great work.
I didn't recognize the gear name in the changelog, so I thought it hadn't been fixed yet. My bad.
