### ISSUE TITLE
Visual glitch with the Karellen FMV on patch 0.4.7

### ISSUE THREAD

**Issue by Kaizoku85** [NoharOSP/Perfect_Works_Build#201]
Using latest DuckStation for Android 0.1-6291-ga38d6928 (dev) Built Jan 25 2024 04:13:09.

According to the changelog it was fixed on patch 0.4.5 but it's still around during that cutscene. Made sure to use ECCRegen after patching. 

I really doubt that the optional USA to JPN controls patcher from the undub patch is related to the FMV glitch. https://www.romhacking.net/hacks/5284/

![Screenshot_2024-08-16-16-09-02-771_com github stenzek duckstation](https://github.com/user-attachments/assets/e7763f1d-4541-4811-86b1-2990a40efdb2)
![Screenshot_2024-08-16-16-09-04-111_com github stenzek duckstation](https://github.com/user-attachments/assets/001a352c-4db0-4c6e-8579-87698bc39726)

**Comment by NoharOSP** [comment]
That's odd as the scene worked fine on the desktop version of Duckstation. I'll give it another test regardless.

**Comment by NoharOSP** [comment]
This seems to work fine with both the latest versions of the desktop Duckstation and Mednafen. I'm have a feeling this is an issue with the Android version of Duckstation. If you have the means to test the desktop version, let me know if the issue persists.

**Comment by Kaizoku85** [comment]
Tested different patched versions with ECCRegen verification and I think I managed to track the cause for the FMV glitch.
After patching with FMV changes, apparently there's some conflict with Half encounters and Script/name changes to cause the FMV Karellen glitch.
![Xenogears_FMV_Glitch_03](https://github.com/user-attachments/assets/a51c1dd0-dce1-4376-b7d6-742729c08740)

The following patching options don't cause the FMV Karellen glitch though.
![Xenogears_No_FMV_Glitch_01](https://github.com/user-attachments/assets/4a962a57-6123-4050-be0b-7aa87e24d0ab)
![Xenogears_No_FMV_Glitch_02](https://github.com/user-attachments/assets/05b67605-42dd-4a52-8112-d9e61db62503)

Used the latest Windows desktop build of Duckstation (0.1-7401-ge91eb82d7)
Hope this info works.

**Comment by NoharOSP** [comment]
Thanks for discovering this. Having tested this for myself, this does indeed trigger the glitch. As version 0.5 will use a different patching method, this should resolve the conflict. I will be sure to credit you for this.
