### ISSUE TITLE
Translation fix

### ISSUE THREAD

**Issue by medallium** [NoharOSP/Perfect_Works_Build#208]
Bart Missiles aka "Gungany".
I believe this is a mis-localization/translation; the correct term should be "Gungnir, to be inline with the Norse mythology theme of the Yggdrasil ship.

(This mistranslation appears when Yggdrasil 2 prepares to shoot down the Goliath in Disc 1)

**Comment by medallium** [comment]
Adding: Elly and Erich dialogue, typographical error for "postion"
![image](https://github.com/user-attachments/assets/2b6e27fe-2a33-47a0-a725-9eba35c627e7)

**Comment by NoharOSP** [comment]
Upon checking the script files, both problems shared were resolved a while back. Are you using the original script?

**Comment by medallium** [comment]
Did a run on steam deck with it's own delta patcher from flathub, not the included PW patcher.
I asssumed the 0.5.3 patch included replaces the script by default.
If both are already resolved, I'll close this issue, thanks!
